version: 1
update_configs:
  - package_manager: "docker"
    directory: "/src"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
  - package_manager: github_actions
    directory: /
    update_schedule: weekly
